version: '3'

services:
  opcrouter5:
    image: opcrouter/runtime:latest
    container_name: opcrouter5
    environment:
      - OR_I_ACCEPT_EULA=true
      - INITIAL_USERNAME=admin
      - INITIAL_PASSWORD=admin
      - TZ=Europe/Berlin
    ports:
      - "8080:8080"
      - "1234:80"
      - "49420:49420"
    volumes:
      - opc-router-5-db:/data/database
      - opc-router-5-userdata:/inray
      - opc-router5-logs:/var/log/opcrouter
    restart: always
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   environment:
  #     - AUTH=yes
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #     #     MONGO_INITDB_DATABASE: opc
  #   volumes:
  #     - mongodb_data_container:/data/db
  #   ports:
  #     - "27018:27017"
  #   networks:
  #     - mongo

volumes:
  opc-router-5-db:
  opc-router-5-userdata:
  opc-router5-logs:
  mongodb_data_container:

